# Generated by Django 5.2.7 on 2025-11-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0014_remove_attendance_attendance_user_checkout_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermembership",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Membership",
                "verbose_name_plural": "User Memberships",
            },
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Set when membership is approved", null=True
            ),
        ),
    ]
